# Generated by go2rpm 1.9.0
%bcond_with check
%bcond_with bootstrap
%global debug_package %{nil}
%global module compute/metadata

# https://github.com/GoogleCloudPlatform/google-cloud-go
%global goipath         cloud.google.com/go/%{module}
%global forgeurl        https://github.com/GoogleCloudPlatform/google-cloud-go
Version:                0.2.3
%global tag             %{module}/v%{version}
%global distprefix      %{nil}

%gometa

%global common_description %{expand:
Go packages for Google Cloud Platform services.}


%global golicenses      LICENSE
%global godocs          CHANGES.md CODE_OF_CONDUCT.md CONTRIBUTING.md\\\
                        README.md RELEASING.md SECURITY.md testing.md\\\

Name:           %{goname}
Release:        %autorelease
Summary:        Google Cloud Client Libraries for Go for module %{module}

License:        BSD-3-Clause AND Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

# remove doc.go from root path to avoid module clash
rm doc.go

# remove all modules but compute/metadata
find %{_builddir}/google-cloud-go-compute-metadata-v%{version}/* -depth -type d -not -path '*/compute*' -not -path '*/_build*' -exec rm -rf {} \;
for i in aliasshim apiv1 internal; do rm -rf compute/$i; done
mv compute/metadata/* .

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
