# Generated by go2rpm 1.10.0
%bcond_without check
%bcond_without bootstrap
%global debug_package %{nil}
%global module googleapis/api/serviceusage

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/google/go-genproto
%global goipath         google.golang.org/genproto/googleapis/api/serviceusage
%global forgeurl        https://github.com/google/go-genproto
%global commit          d783a09b4405a1cd1cf45a3ca26e53c9854f603f

%gometa -L


%global common_description %{expand:
Generated code for Google Cloud client libraries.}

%global golicenses      LICENSE
%global godocs          CODE_OF_CONDUCT.md CONTRIBUTING.md README.md\\\
                        RELEASING.md SECURITY.md

Name:           golang-google-genproto-googleapis-api-serviceusage
Version:        0
Release:        %autorelease -p
Summary:        Generated code for Google Cloud client libraries

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1
find . ! \( -name googleapis -o -name "*.md" -o -name LICENSE -o -name _build \) -maxdepth 1 -exec rm -rvf {} \;
mv %{module}/* .
rm -rfv googleapis

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
