# Generated by go2rpm
%bcond_without check

# https://github.com/google/flatbuffers
%global goipath         github.com/google/flatbuffers
Version:                1.12.0

%gometa

%global common_description %{expand:
FlatBuffers is a cross platform serialization library architected for maximum
memory efficiency. It allows you to directly access serialized data without
parsing/unpacking it first, while still having great forwards/backwards
compatibility.}

%global golicenses      LICENSE.txt
%global godocs          CONTRIBUTING.md readme.md

Name:           %{goname}
Release:        9%{?dist}
Summary:        Memory Efficient Serialization Library

License:        Apache-2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(google.golang.org/grpc)

%description
%{common_description}

%gopkg

%prep
%goprep
# Remove files unrelated to the Go Library
find ./* -maxdepth 0 -type d -not -name "go" -and -not -name "_build" -exec rm -rf "{}" \;

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Oct 05 2023 W. Michael Petullo <mike@flyn.org> - 1.12.0-9
- Use SPDX license nomenclature

* Thu Jul 20 2023 Fedora Release Engineering <releng@fedoraproject.org> - 1.12.0-8
- Rebuilt for https://fedoraproject.org/wiki/Fedora_39_Mass_Rebuild

* Thu Jan 19 2023 Fedora Release Engineering <releng@fedoraproject.org> - 1.12.0-7
- Rebuilt for https://fedoraproject.org/wiki/Fedora_38_Mass_Rebuild

* Thu Jul 21 2022 Fedora Release Engineering <releng@fedoraproject.org> - 1.12.0-6
- Rebuilt for https://fedoraproject.org/wiki/Fedora_37_Mass_Rebuild

* Thu Jan 20 2022 Fedora Release Engineering <releng@fedoraproject.org> - 1.12.0-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_36_Mass_Rebuild

* Thu Jul 22 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.12.0-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_35_Mass_Rebuild

* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.12.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Mon Jul 27 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.12.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Sun Jul 26 22:30:54 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 1.12.0-1
- Update to 1.12.0

* Wed Jan 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.11.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Thu Jul 25 2019 Fedora Release Engineering <releng@fedoraproject.org> - 1.11.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Tue May 14 21:15:25 CEST 2019 Robert-André Mauchin <zebob.m@gmail.com> - 1.11.0-1
- Initial package
