# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/googleapis/gax-go
%global goipath         github.com/googleapis/gax-go
Version:                2.12.0

%gometa

%global common_description %{expand:
Google API Extensions for Go.}

%global golicenses      LICENSE
%global godocs          CODE_OF_CONDUCT.md CONTRIBUTING.md RELEASING.md\\\
                        SECURITY.md README.md v2/CHANGES.md

Name:           %{goname}
Release:        %autorelease
Summary:        Google API Extensions for Go

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
